# Site settings
title: Knee Deep in the Code
header-img: img/home-bg.png
email: mfcrooks@gmail.com
copyright_name: mcrooks65
description: > # this means to ignore newlines until "baseurl:"
  Teach Me Plenty
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mcrooks65
learn_profile: mcrooks65
email_username: mfcrooks@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
